version: "3.9"

services:
  # catalog.api:
  #   container_name: catalog.api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:8080"
  #   depends_on:
  #     - catalog.mongo
  #   environment:
  #     DatabaseSettings__ConnectionString: "mongodb://catalog.mongo:27017"
  #     DatabaseSettings__DatabaseName: "CatalogDb"
  #     DatabaseSettings__ProductsCollectionName: "Products"

  catalog.mongo:
    container_name: catalog.mongo
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalog-mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: "CatalogDb"

volumes:
  catalog-mongo-data:
